services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\Application\CommandHandler\Pet\CreatePetHandler:
        arguments:
            - '@App\Domain\Pet\PetFactory'
            - '@App\Infrastructure\Repository\PetDoctrineRepository'
        tags:
            - { name: messenger.message_handler }

    App\Application\CommandHandler\Shelter\CreateShelterHandler:
        arguments:
            - '@App\Domain\Shelter\ShelterFactory'
            - '@App\Infrastructure\Repository\ShelterDoctrineRepository'
        tags:
            - { name: messenger.message_handler }
