services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\Infrastructure\Security\Provider\AdminUserProvider:
        arguments:
            - '@App\Infrastructure\Doctrine\Repository\AdminUserRepository'
