security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        admin_users:
            entity:
                class: 'App\Domain\AdminUser\AdminUser'
                property: 'email'
        front_users:
            entity:
                class: 'App\Domain\FrontUser\FrontUser'
                property: 'email'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_admin_authentication:
            pattern: ^/api/admin/authenticate$
            provider: admin_users
            stateless: true
            json_login:
                check_path: admin_user_authenticate
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api_front_authentication:
            pattern: ^/api/front/authenticate$
            provider: front_users
            stateless: true
            json_login:
                check_path: front_user_authenticate
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api_admin:
            pattern: ^/api/admin
            provider: admin_users
            stateless: true
            jwt: ~
        api_front:
            pattern: /^api/front
            provider: front_users
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/admin/authenticate$, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
