services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\Infrastructure\ApiPlatform\Bridge\Symfony\Provider\PathPrefixProvider:
        arguments:
            - '@App\Infrastructure\Context\TokenBasedUserContext'
            - '%api_prefix%'
