services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\Infrastructure\DataFixtures\Faker\Provider\IdProvider:
        tags:
            - { name: nelmio_alice.faker.provider }
