parameters:
    api_authorization_header: 'Authorization'
    api_prefix: '/api'

imports:
    - { resource: "./services/**/*.yaml" }

services:
    _defaults:
        autowire: false
        autoconfigure: false
