services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\Infrastructure\Doctrine\QueryCollectionExtension\ShelterCollectionExtension:
        tags:
            - { name: 'api_platform.doctrine.orm.query_extension.collection' }

    App\Infrastructure\Doctrine\QueryItemExtension\ShelterItemExtension:
        tags:
            - { name: 'api_platform.doctrine.orm.query_extension.item' }
