services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\Infrastructure\Doctrine\Repository\AdminUserRepository:
        arguments:
            - '@doctrine.orm.entity_manager'

    App\Infrastructure\Doctrine\Repository\ShelterRepository:
        arguments:
            - '@doctrine.orm.entity_manager'
